In [2]:
import pandas as pd
import numpy as np

In [5]:
df_albany = pd.read_csv('../cleaned-data-frames/albany.csv')
df_buffalo = pd.read_csv('../cleaned-data-frames/buffalo.csv')
target = pd.read_csv('../cleaned-data-frames/target-electricity-consumption.csv')

In [6]:
df_albany

,Unnamed: 0,Unnamed: 0.1,name,time,month,day,hourly_temperature,hourly_wind_speed,AWT26_Power,AWP_200_Power,D2CF_200_Power,AN_Bonus_150/30_Power,Aria_20_Power,WWD-1_D64_Power,solar,Solar_AllMax,Solar_TrinaSolar,Solar_Mitsubishi,Solar_FirstSolar
0,0,26277,"ALBANY INTERNATIONAL AIRPORT, NY US",1,1,1,-4.1,3.6,22.503703,23.181080,52.775842,33.680575,6.010686,284.762185,0.0,0.0,0.0,0.0,0.0
1,1,26278,"ALBANY INTERNATIONAL AIRPORT, NY US",2,1,1,-4.2,3.6,22.503703,23.181080,52.775842,33.680575,6.010686,284.762185,0.0,0.0,0.0,0.0,0.0
2,2,26279,"ALBANY INTERNATIONAL AIRPORT, NY US",3,1,1,-4.4,3.5,19.239583,19.879067,48.847905,30.226074,5.689710,264.743208,0.0,0.0,0.0,0.0,0.0
3,3,26280,"ALBANY INTERNATIONAL AIRPORT, NY US",4,1,1,-4.5,3.6,22.503703,23.181080,52.775842,33.680575,6.010686,284.762185,0.0,0.0,0.0,0.0,0.0
4,4,26281,"ALBANY INTERNATIONAL AIRPORT, NY US",5,1,1,-4.7,3.6,22.503703,23.181080,52.775842,33.680575,6.010686,284.762185,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,8754,35031,"ALBANY INTERNATIONAL AIRPORT, NY US",19,12,31,-2.6,3.9,33.648570,33.607124,64.441728,44.678486,6.987303,345.810304,0.0,0.0,0.0,0.0,0.0
8755,8755,35032,"ALBANY INTERNATIONAL AIRPORT, NY US",20,12,31,-2.8,3.9,33.648570,33.607124,64.441728,44.678486,6.987303,345.810304,0.0,0.0,0.0,0.0,0.0
8756,8756,35033,"ALBANY INTERNATIONAL AIRPORT, NY US",21,12,31,-3.1,3.8,29.708200,30.069277,60.537502,40.932784,6.659245,325.120255,0.0,0.0,0.0,0.0,0.0
8757,8757,35034,"ALBANY INTERNATIONAL AIRPORT, NY US",22,12,31,-3.3,3.8,29.708200,30.069277,60.537502,40.932784,6.659245,325.120255,0.0,0.0,0.0,0.0,0.0
8758,8758,35035,"ALBANY INTERNATIONAL AIRPORT, NY US",23,12,31,-3.6,3.7,25.993066,26.586012,56.660182,37.258288,6.333786,304.825735,0.0,0.0,0.0,0.0,0.0

In [7]:
df_buffalo

,Unnamed: 0,Unnamed: 0.1,name,time,month,day,hourly_temperature,hourly_wind_speed,AWT26_Power,AWP_200_Power,D2CF_200_Power,AN_Bonus_150/30_Power,Aria_20_Power,WWD-1_D64_Power,solar,Solar_AllMax,Solar_TrinaSolar,Solar_Mitsubishi,Solar_FirstSolar
0,0,8759,"BUFFALO NIAGARA INTERNATIONAL, NY US",1,1,1,-2.8,5.2,102.934779,76.801536,125.063123,91.274220,11.536541,674.053746,0.0,0.0,0.0,0.0,0.0
1,1,8760,"BUFFALO NIAGARA INTERNATIONAL, NY US",2,1,1,-3.0,5.1,96.666535,73.917454,119.772045,88.134760,11.170466,646.115550,0.0,0.0,0.0,0.0,0.0
2,2,8761,"BUFFALO NIAGARA INTERNATIONAL, NY US",3,1,1,-3.1,5.1,96.666535,73.917454,119.772045,88.134760,11.170466,646.115550,0.0,0.0,0.0,0.0,0.0
3,3,8762,"BUFFALO NIAGARA INTERNATIONAL, NY US",4,1,1,-3.1,5.1,96.666535,73.917454,119.772045,88.134760,11.170466,646.115550,0.0,0.0,0.0,0.0,0.0
4,4,8763,"BUFFALO NIAGARA INTERNATIONAL, NY US",5,1,1,-3.2,5.1,96.666535,73.917454,119.772045,88.134760,11.170466,646.115550,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,8754,17513,"BUFFALO NIAGARA INTERNATIONAL, NY US",19,12,31,-2.0,5.5,122.210209,84.994288,140.955951,100.134501,12.637616,756.203268,0.0,0.0,0.0,0.0,0.0
8755,8755,17514,"BUFFALO NIAGARA INTERNATIONAL, NY US",20,12,31,-2.2,5.5,122.210209,84.994288,140.955951,100.134501,12.637616,756.203268,0.0,0.0,0.0,0.0,0.0
8756,8756,17515,"BUFFALO NIAGARA INTERNATIONAL, NY US",21,12,31,-2.3,5.4,115.724856,82.333473,135.685140,97.271762,12.270814,729.275412,0.0,0.0,0.0,0.0,0.0
8757,8757,17516,"BUFFALO NIAGARA INTERNATIONAL, NY US",22,12,31,-2.4,5.4,115.724856,82.333473,135.685140,97.271762,12.270814,729.275412,0.0,0.0,0.0,0.0,0.0
8758,8758,17517,"BUFFALO NIAGARA INTERNATIONAL, NY US",23,12,31,-2.6,5.4,115.724856,82.333473,135.685140,97.271762,12.270814,729.275412,0.0,0.0,0.0,0.0,0.0

In [8]:
df_combined = pd.merge(df_albany,df_buffalo,on=['time','month','day'])

In [9]:
df_combined.iloc[:,9:]

,Unnamed: 0_x,Unnamed: 0.1_x,name_x,time,month,day,hourly_temperature_x,hourly_wind_speed_x,AWT26_Power_x,AWP_200_Power_x,...,AWP_200_Power_y,D2CF_200_Power_y,AN_Bonus_150/30_Power_y,Aria_20_Power_y,WWD-1_D64_Power_y,solar_y,Solar_AllMax_y,Solar_TrinaSolar_y,Solar_Mitsubishi_y,Solar_FirstSolar_y
0,0,26277,"ALBANY INTERNATIONAL AIRPORT, NY US",1,1,1,-4.1,3.6,22.503703,23.181080,...,76.801536,125.063123,91.274220,11.536541,674.053746,0.0,0.0,0.0,0.0,0.0
1,1,26278,"ALBANY INTERNATIONAL AIRPORT, NY US",2,1,1,-4.2,3.6,22.503703,23.181080,...,73.917454,119.772045,88.134760,11.170466,646.115550,0.0,0.0,0.0,0.0,0.0
2,2,26279,"ALBANY INTERNATIONAL AIRPORT, NY US",3,1,1,-4.4,3.5,19.239583,19.879067,...,73.917454,119.772045,88.134760,11.170466,646.115550,0.0,0.0,0.0,0.0,0.0
3,3,26280,"ALBANY INTERNATIONAL AIRPORT, NY US",4,1,1,-4.5,3.6,22.503703,23.181080,...,73.917454,119.772045,88.134760,11.170466,646.115550,0.0,0.0,0.0,0.0,0.0
4,4,26281,"ALBANY INTERNATIONAL AIRPORT, NY US",5,1,1,-4.7,3.6,22.503703,23.181080,...,73.917454,119.772045,88.134760,11.170466,646.115550,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,8754,35031,"ALBANY INTERNATIONAL AIRPORT, NY US",19,12,31,-2.6,3.9,33.648570,33.607124,...,84.994288,140.955951,100.134501,12.637616,756.203268,0.0,0.0,0.0,0.0,0.0
8755,8755,35032,"ALBANY INTERNATIONAL AIRPORT, NY US",20,12,31,-2.8,3.9,33.648570,33.607124,...,84.994288,140.955951,100.134501,12.637616,756.203268,0.0,0.0,0.0,0.0,0.0
8756,8756,35033,"ALBANY INTERNATIONAL AIRPORT, NY US",21,12,31,-3.1,3.8,29.708200,30.069277,...,82.333473,135.685140,97.271762,12.270814,729.275412,0.0,0.0,0.0,0.0,0.0
8757,8757,35034,"ALBANY INTERNATIONAL AIRPORT, NY US",22,12,31,-3.3,3.8,29.708200,30.069277,...,82.333473,135.685140,97.271762,12.270814,729.275412,0.0,0.0,0.0,0.0,0.0
8758,8758,35035,"ALBANY INTERNATIONAL AIRPORT, NY US",23,12,31,-3.6,3.7,25.993066,26.586012,...,82.333473,135.685140,97.271762,12.270814,729.275412,0.0,0.0,0.0,0.0,0.0